### ISSUE TITLE
apply for taxibj dataset

### ISSUE THREAD

**Issue by nana1223** [Pachark/SVQ-Forecasting#1]
hi, taxibj dataset link is invalid.
Could you repost it? Or send to my email [zhangna1998zn@163.com](mailto:zhangna1998zn@163.com)
thank you!!!

**Comment by Pachark** [comment]
Hi, you may refer to [OpenSTL README](https://github.com/chengtan9907/OpenSTL/blob/OpenSTL-Lightning/docs/en/install.md) and download datasets from [Baidu Cloud](https://pan.baidu.com/s/1fudsBHyrf3nbt-7d42YWWg?pwd=kjfk) (kjfk), which is also the version we used in our experiments.
